Document: libva-rockchip
Title: Debian libva-rockchip Manual
Author: <insert document author here>
Abstract: This manual describes what libva-rockchip is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libva-rockchip/libva-rockchip.sgml.gz

Format: postscript
Files: /usr/share/doc/libva-rockchip/libva-rockchip.ps.gz

Format: text
Files: /usr/share/doc/libva-rockchip/libva-rockchip.text.gz

Format: HTML
Index: /usr/share/doc/libva-rockchip/html/index.html
Files: /usr/share/doc/libva-rockchip/html/*.html
